import Image from 'next/image'
import React from 'react'
import { motion } from 'framer-motion'
import Text from '../UI/Text'

function Sample() {
  return (
    <div
      className="xl:max-w-[1200px] max-w-[90%] mx-auto md:py- py-20 "
      id="sample"
    >
      <motion.div
        className="w-full"
        initial={{ opacity: 0, y: 50 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 1 }}
        viewport={{ once: false }}
      >
        <Text as="h2" className="text-center md:max-w-[80%] mx-auto">
          <span className="text-[#266CAB]">Sample </span>Images
        </Text>
        <Text
          as="p1"
          className="text-center text-[#00000066] mx-auto  max-w-[90%]"
        >
          See how our software transforms the input image into precise,
          production-ready DXF files for your custom tool drawer inserts.
        </Text>
      </motion.div>
      {/* upper images */}
      <div className="flex md:flex-row flex-col justify-center md:mt-10 mt-5  md:gap-10 gap-[40px] items-start">
        {/* Left Image */}
        <motion.div
          className="relative md:w-2/3 w-full h-auto md:h-auto"
          initial={{ opacity: 0, y: 50 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 1 }}
          viewport={{ once: false }}
        >
          <Image
            src="/images/user/home/sample/input.svg"
            alt="overlay Image"
            width={500}
            height={500}
            className="w-full h-auto"
          />
          <p className="text-start mt-5 font-semibold text-4xl">Input Image</p>
        </motion.div>

        {/* Right Image */}
        <motion.div
          className="relative md:w-2/3 w-full h-auto md:h-auto mt-0"
          initial={{ opacity: 0, y: -50 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: false }}
        >
          <Image
            src="/images/user/home/sample/mask.svg"
            alt="preview Image"
            width={500}
            height={500}
            className="w-full h-auto"
          />
          <p className="text-start mt-5 font-semibold text-4xl">Mask</p>
          <p className="font-medium md:text-2xl text-lg text-[#00000080]">
            Isolates tool contours, providing the precise geometry needed to
            generate accurate DXF contours.
          </p>
        </motion.div>
      </div>

      {/* lower images */}
      <div className="flex md:flex-row flex-col justify-center mt-10   md:gap-10 gap-[50px] items-start">
        {/* Left Image */}
        <motion.div
          className="relative md:w-2/3 w-full h-auto md:h-auto "
          initial={{ opacity: 0, y: -50 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: false }}
        >
          <Image
            src="/images/user/home/sample/overlay.svg"
            alt="overlay Image"
            width={500}
            height={500}
            className="w-full h-auto"
          />
          <p className="text-start mt-5 font-semibold text-4xl">Overlay</p>
          <p className="font-medium md:text-2xl text-lg text-[#00000080]">
            DXF contours (in red) overlayed onto the input image with the
            optional offset parameter applied, allowing users to confirm
            accurate tool edge detection.
          </p>
        </motion.div>

        {/* Right Image */}
        <motion.div
          className="relative md:w-2/3 w-full h-auto md:h-auto mt-0"
          initial={{ opacity: 0, y: 50 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: false }}
        >
          <Image
            src="/images/user/home/sample/preview.svg"
            alt="preview Image"
            width={500}
            height={500}
            className="w-full h-auto"
          />
          <p className="text-start mt-5 font-semibold text-4xl">DXF Preview</p>
          <p className="font-medium md:text-2xl text-lg text-[#00000080]">
            Previews the DXF contours generated by the software (optional
            bounding box not included in this DXF).
          </p>
        </motion.div>
      </div>
    </div>
  )
}

export default Sample
