import Image from 'next/image'
import React from 'react'

function Sample() {
    return (
        <div className='max-w-[90%] mx-auto md:py- py-20 ' id='sample'>
            <p className='font-bold md:text-[55px] text-[40px] text-center md:max-w-[80%] mx-auto'><span className='text-[#266CAB]'>Sample </span>Images</p>
            <p className='text-center text-[#00000066] md:text-[29px] text-[23px] mx-auto font-medium max-w-[90%]'>See how our software transforms the input image into precise, production-ready DXF files for your custom tool drawer inserts.</p>
            {/* upper images */}
            <div className="flex md:flex-row flex-col justify-center md:mt-10 mt-5 lg:mx-14 2xl:mx-24 md:gap-0 gap-22 items-start">
                {/* Left Image */}
                <div className="relative md:w-1/3 lg:w-full aspect-[10/9]">
                    <div className="relative w-full h-full">
                        <Image src="/images/user/home/sample/input.svg" alt="overlay Image" fill />
                    </div>
                    <p className="text-start mt-5 ms-5 font-semibold text-4xl">Input Image</p>
                    <p className="font-medium md:text-xl text-lg text-[#00000080] ms-5 invisible">
                        DXF contours (in red) overlayed onto the input image with the optional offset parameter applied, allowing users to confirm accurate tool edge detection.
                    </p>
                </div>

                {/* Right Image */}
                <div className="relative md:w-1/3 lg:w-full aspect-[10/9] mt-0">
                    <div className="relative w-full h-full">
                        <Image src="/images/user/home/sample/mask.svg" alt="preview Image" fill />
                    </div>
                    <p className="text-start mt-5 ms-5 font-semibold text-4xl">Mask</p>
                    {/* Removed the text but maintained the alignment */}
                    <p className="font-medium md:text-xl text-lg text-[#00000080] ms-5">
                    Isolates tool contours, providing the precise geometry needed to generate accurate DXF contours.
                    </p>
                </div>
            </div>

            {/* lower images */}
            <div className="flex md:flex-row flex-col justify-center md:mt-10 mt-50 lg:mx-14 2xl:mx-24   md:gap-0 gap-22">
                {/* Left Image */}
                <div className="relative md:w-1/3 lg:w-2/3 aspect-[10/9] ">
                    <div className="relative w-full h-full">
                        <Image
                            src="/images/user/home/sample/overlay.svg"
                            alt="overlay Image"
                            fill
                        />
                    </div>
                    <p className="text-start mt-5 ms-5 font-semibold text-4xl">Overlay</p>
                    <p className='font-medium md:text-xl text-lg text-[#00000080] ms-5'>DXF contours (in red) overlayed onto the input image with the optional offset parameter applied, allowing users to confirm accurate tool edge detection.</p>

                </div>


                {/* Right Image */}
                <div className="relative md:w-1/3 lg:w-2/3 aspect-[10/9] md:mt-0 mt-30">
                    <div className="relative w-full h-full">
                        <Image
                            src="/images/user/home/sample/preview.svg"
                            alt="preview Image"
                            fill
                        />
                    </div>
                    <p className="text-start mt-5 ms-5 font-semibold text-4xl">DXF Preview</p>
                    <p className='font-medium md:text-xl text-lg text-[#00000080] ms-5'>Previews the DXF contours generated by the software (optional bounding box not included in this DXF). <span className='invisible'>gdgxxdgxdg gxsss gsxxsgsx</span></p>
                </div>
            </div>
        </div>
    )
}

export default Sample
